//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financeiro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financeiro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [Transaction];
        ///DROP TABLE IF EXISTS [Entity];
        ///DROP TABLE IF EXISTS [Source];
        ///DROP TABLE IF EXISTS [Category];
        ///DROP TABLE IF EXISTS [Settings];
        ///DROP TABLE IF EXISTS [CategoryRelationship];
        ///DROP TABLE IF EXISTS [Error];
        ///DROP TABLE IF EXISTS [Report];
        ///DROP TABLE IF EXISTS [TransactionReport];
        ///DROP TABLE IF EXISTS [ToUpload];
        ///DROP TABLE IF EXISTS [PaymentMethod];
        ///DROP TABLE IF EXISTS [TransactionPayment];
        ///
        ///CREATE TABLE [Entity] (
        ///	[RegistrationDate] INTEGER PRIMARY KEY NOT NULL,
        ///	[Name] TEX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseCreation {
            get {
                return ResourceManager.GetString("DatabaseCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [PaymentMethod] values (1, &apos;Dinheiro&apos;), (2, &apos;Débito&apos;), (3, &apos;Crédito&apos;);
        ///
        ///insert into [Source] values (1, &apos;Sqlite&apos;), (2, &apos;MySql&apos;), (3, &apos;DynamoDB&apos;);
        ///
        ///insert into [Settings] values (&apos;Database&apos;, &apos;clinica2&apos;), (&apos;UserID&apos;, &apos;root&apos;), (&apos;Password&apos;, &apos;1025&apos;), (&apos;Server&apos;, &apos;192.168.0.3&apos;);
        ///
        ///insert into [Entity] values (1, &apos;Clinica&apos;), (2, &apos;Paciente&apos;);.
        /// </summary>
        internal static string InitialData {
            get {
                return ResourceManager.GetString("InitialData", resourceCulture);
            }
        }
    }
}
